apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-cafe-web
spec:
  template:
    spec:
      containers:
        - name: quarkus-cafe-web
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: cafe-cluster-kafka-bootstrap:9092
            - name: REST_URL
              value: http://quarkus-cafe-web-quarkus-cafe-demo.apps.ocp4.example.com
            - name: STREAM_URL
              value:  http://quarkus-cafe-web-quarkus-cafe-demo.apps.ocp4.example.com/dashboard/stream
            - name: CORS_ORIGINS
              value: http://quarkus-cafe-demo.apps.ocp4.example.com